"""
src/services/auto_signal_linter.py
====================================
Story 179 — AutoSignalLinter: auto-fix de geometria do sinal.

Inspirado no padrão Aider auto-lint:
  "Aider can automatically lint and test your code every time it makes
   changes, fixing problems detected by your linters."

Ao contrário do SignalValidator (que *bloqueia* sinais inválidos),
o AutoSignalLinter *corrige* problemas de geometria antes de passar
para o SignalValidator. A direção do sinal (LONG/SHORT/HOLD) é preservada;
apenas valores fora de range ou invertidos são reparados.

Regras de correção (em ordem de aplicação)
------------------------------------------
1. confidence: clamp para [0.0, 1.0]
2. entry_price: se <= 0, usa last_known_price ou fica None
3. stop_loss / take_profit: se SL >= TP em LONG, troca os dois
4. stop_loss / take_profit: se SL <= TP em SHORT, troca os dois
5. leverage: clamp para [1.0, settings.max_leverage]
6. risk_pct: clamp para [0.001, settings.max_risk_per_trade_pct]
7. reasoning: se None ou vazio, preenche com fallback genérico

Cada correção é registrada em `LintResult.fixes` com um diff legível
(padrão SEARCH/REPLACE de aider/editblock_coder.py).

Uso
---
    from src.services.auto_signal_linter import get_auto_signal_linter

    linter = get_auto_signal_linter()
    result = linter.lint(signal, last_price=94320.0)
    if result.was_fixed:
        signal = result.fixed_signal  # sinal corrigido
        print(result.summary())       # log das correções
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Optional

from loguru import logger


# ---------------------------------------------------------------------------
# LintFix — uma correção individual (SEARCH/REPLACE style)
# ---------------------------------------------------------------------------

@dataclass
class LintFix:
    """
    Representa uma correção feita pelo linter.
    Formato inspirado no SEARCH/REPLACE do aider/editblock_coder.py.
    """
    field: str
    before: Any
    after: Any
    rule: str

    def to_search_replace(self) -> str:
        """Formata a correção no estilo diff SEARCH/REPLACE do Aider."""
        return (
            f"<<<<<<< SEARCH\n"
            f"{self.field}: {self.before}\n"
            f"=======\n"
            f"{self.field}: {self.after}\n"
            f">>>>>>> REPLACE\n"
            f"# Rule: {self.rule}"
        )

    def to_dict(self) -> dict:
        return {
            "field": self.field,
            "before": self.before,
            "after": self.after,
            "rule": self.rule,
        }


# ---------------------------------------------------------------------------
# LintResult
# ---------------------------------------------------------------------------

@dataclass
class LintResult:
    """
    Resultado do processo de lint de um sinal.
    """
    original_signal: Any
    fixed_signal: Any
    fixes: list[LintFix] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)

    @property
    def was_fixed(self) -> bool:
        """True se pelo menos uma correção foi aplicada."""
        return len(self.fixes) > 0

    @property
    def has_errors(self) -> bool:
        """True se houve erros que impediu alguma correção."""
        return len(self.errors) > 0

    def summary(self) -> str:
        """Sumário legível das correções aplicadas."""
        if not self.fixes:
            return "AutoSignalLinter: no fixes needed"
        lines = [f"AutoSignalLinter: {len(self.fixes)} fix(es) applied"]
        for fix in self.fixes:
            lines.append(f"  [{fix.field}] {fix.before!r} → {fix.after!r} ({fix.rule})")
        return "\n".join(lines)

    def to_dict(self) -> dict:
        return {
            "was_fixed": self.was_fixed,
            "fix_count": len(self.fixes),
            "fixes": [f.to_dict() for f in self.fixes],
            "errors": self.errors,
            "summary": self.summary(),
        }


# ---------------------------------------------------------------------------
# AutoSignalLinter
# ---------------------------------------------------------------------------

class AutoSignalLinter:
    """
    Linter automático para TradingSignal — corrige geometria antes de
    passar para o SignalValidator (Story 158).

    Padrão Aider: "fixes problems detected by your linters" ao invés de
    apenas reportar e bloquear.
    """

    def __init__(
        self,
        max_leverage: float = 20.0,
        max_risk_pct: float = 0.05,
        min_confidence: float = 0.0,
        max_confidence: float = 1.0,
        fallback_reasoning: str = "Signal generated by Vision — no explicit reasoning provided.",
    ) -> None:
        self.max_leverage = max_leverage
        self.max_risk_pct = max_risk_pct
        self.min_confidence = min_confidence
        self.max_confidence = max_confidence
        self.fallback_reasoning = fallback_reasoning

    def lint(
        self,
        signal: Any,
        last_price: Optional[float] = None,
    ) -> LintResult:
        """
        Aplica todas as regras de correção ao sinal.

        Args:
            signal: TradingSignal (ou objeto com campos compatíveis)
            last_price: preço mais recente do ativo (para corrigir entry_price=0)

        Returns:
            LintResult com o sinal (possivelmente corrigido) e lista de fixes.
        """
        fixes: list[LintFix] = []
        errors: list[str] = []

        # Trabalha em cópia para não mutar o original
        try:
            updated = {}

            # --- Regra 1: confidence clamp ---
            conf = getattr(signal, "confidence", None)
            if conf is not None:
                try:
                    conf_f = float(conf)
                    clamped = max(self.min_confidence, min(self.max_confidence, conf_f))
                    if abs(clamped - conf_f) > 1e-9:
                        fixes.append(LintFix(
                            field="confidence",
                            before=conf_f,
                            after=round(clamped, 4),
                            rule="clamp [0.0, 1.0]",
                        ))
                        updated["confidence"] = round(clamped, 4)
                except (TypeError, ValueError):
                    errors.append(f"confidence: cannot convert {conf!r} to float")

            # --- Regra 2: entry_price <= 0 ---
            entry = getattr(signal, "entry_price", None)
            if entry is not None:
                try:
                    entry_f = float(entry)
                    if entry_f <= 0:
                        replacement = last_price if last_price and last_price > 0 else None
                        fixes.append(LintFix(
                            field="entry_price",
                            before=entry_f,
                            after=replacement,
                            rule="entry_price <= 0 → use last_price or None",
                        ))
                        updated["entry_price"] = replacement
                except (TypeError, ValueError):
                    errors.append(f"entry_price: cannot convert {entry!r} to float")

            # --- Regras 3 & 4: SL/TP invertido ---
            sl = getattr(signal, "stop_loss", None)
            tp = getattr(signal, "take_profit", None)
            action = getattr(signal, "action", None)
            action_str = str(action.value if hasattr(action, "value") else action).upper()

            if sl is not None and tp is not None:
                try:
                    sl_f = float(sl)
                    tp_f = float(tp)

                    is_long = action_str in ("LONG", "BUY", "STRONG_BUY")
                    is_short = action_str in ("SHORT", "SELL", "STRONG_SELL")

                    # LONG: SL deve ser < entry < TP
                    if is_long and sl_f >= tp_f:
                        fixes.append(LintFix(
                            field="stop_loss/take_profit",
                            before=f"SL={sl_f}, TP={tp_f}",
                            after=f"SL={tp_f}, TP={sl_f} (swapped)",
                            rule="LONG: stop_loss >= take_profit → swap",
                        ))
                        updated["stop_loss"] = tp_f
                        updated["take_profit"] = sl_f

                    # SHORT: SL deve ser > entry > TP
                    elif is_short and sl_f <= tp_f:
                        fixes.append(LintFix(
                            field="stop_loss/take_profit",
                            before=f"SL={sl_f}, TP={tp_f}",
                            after=f"SL={tp_f}, TP={sl_f} (swapped)",
                            rule="SHORT: stop_loss <= take_profit → swap",
                        ))
                        updated["stop_loss"] = tp_f
                        updated["take_profit"] = sl_f

                except (TypeError, ValueError):
                    errors.append(f"SL/TP: cannot compare {sl!r} and {tp!r}")

            # --- Regra 5: leverage clamp ---
            leverage = getattr(signal, "leverage", None)
            if leverage is not None:
                try:
                    lev_f = float(leverage)
                    clamped_lev = max(1.0, min(self.max_leverage, lev_f))
                    if abs(clamped_lev - lev_f) > 1e-9:
                        fixes.append(LintFix(
                            field="leverage",
                            before=lev_f,
                            after=round(clamped_lev, 1),
                            rule=f"clamp [1.0, {self.max_leverage}]",
                        ))
                        updated["leverage"] = round(clamped_lev, 1)
                except (TypeError, ValueError):
                    errors.append(f"leverage: cannot convert {leverage!r} to float")

            # --- Regra 6: risk_pct clamp ---
            risk_pct = getattr(signal, "risk_pct", None)
            if risk_pct is not None:
                try:
                    risk_f = float(risk_pct)
                    clamped_risk = max(0.001, min(self.max_risk_pct, risk_f))
                    if abs(clamped_risk - risk_f) > 1e-9:
                        fixes.append(LintFix(
                            field="risk_pct",
                            before=risk_f,
                            after=round(clamped_risk, 4),
                            rule=f"clamp [0.001, {self.max_risk_pct}]",
                        ))
                        updated["risk_pct"] = round(clamped_risk, 4)
                except (TypeError, ValueError):
                    errors.append(f"risk_pct: cannot convert {risk_pct!r} to float")

            # --- Regra 7: reasoning ausente ---
            reasoning = getattr(signal, "reasoning", None)
            if not reasoning or (isinstance(reasoning, str) and not reasoning.strip()):
                fixes.append(LintFix(
                    field="reasoning",
                    before=repr(reasoning),
                    after=repr(self.fallback_reasoning[:80] + "..."),
                    rule="reasoning empty → fallback",
                ))
                updated["reasoning"] = self.fallback_reasoning

            # Aplica updates via model_copy se disponível, senão tenta __dict__
            if updated:
                try:
                    fixed = signal.model_copy(update=updated)
                except AttributeError:
                    # Fallback: mutação direta (dataclass ou plain object)
                    try:
                        import copy
                        fixed = copy.copy(signal)
                        for k, v in updated.items():
                            setattr(fixed, k, v)
                    except Exception:
                        fixed = signal  # fail-safe: retorna original
            else:
                fixed = signal

        except Exception as exc:  # noqa: BLE001
            logger.debug(f"[AutoSignalLinter] lint failed: {exc}")
            errors.append(str(exc))
            fixed = signal

        return LintResult(
            original_signal=signal,
            fixed_signal=fixed,
            fixes=fixes,
            errors=errors,
        )

    def lint_and_log(
        self,
        signal: Any,
        last_price: Optional[float] = None,
        symbol: str = "",
    ) -> Any:
        """
        Atalho: lint + log se houve fixes, retorna o sinal (possivelmente corrigido).
        Armazena o resultado em self._last_result para consumo pelo ObservationFeedbackLoop (Story 191).
        Fail-silent: qualquer exceção → retorna sinal original.
        """
        self._last_result: Optional[Any] = None
        try:
            result = self.lint(signal, last_price=last_price)
            self._last_result = result
            if result.was_fixed:
                logger.info(f"[AutoSignalLinter] {symbol or 'signal'}: {result.summary()}")
            return result.fixed_signal
        except Exception as exc:  # noqa: BLE001
            logger.debug(f"[AutoSignalLinter] lint_and_log failed: {exc}")
            return signal


# ---------------------------------------------------------------------------
# Singleton
# ---------------------------------------------------------------------------

_linter: Optional[AutoSignalLinter] = None


def get_auto_signal_linter() -> AutoSignalLinter:
    """Retorna o singleton global do AutoSignalLinter."""
    global _linter
    if _linter is None:
        try:
            from src.config.settings import settings
            max_leverage = float(getattr(settings, "max_leverage", 20.0))
            max_risk_pct = float(getattr(settings, "max_risk_per_trade_pct", 0.05))
        except Exception:  # noqa: BLE001
            max_leverage = 20.0
            max_risk_pct = 0.05
        _linter = AutoSignalLinter(
            max_leverage=max_leverage,
            max_risk_pct=max_risk_pct,
        )
    return _linter


def reset_auto_signal_linter() -> None:
    """Reseta o singleton — para testes."""
    global _linter
    _linter = None
